import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function exportNINCertPDF(record) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();
  const r = record.result || {};

  // Header bar (purple, slightly different shade)
  doc.setFillColor(79, 70, 229);
  doc.rect(0, 0, W, 38, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('NIN Verification Certificate', 14, 16);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 24);
  doc.text(`Lucred Credit Engine · Confidential`, 14, 30);

  // Photo (returned from Dojah in live result; stored in DB for history)
  if (r.photo) {
    try {
      const imgData = r.photo.startsWith('data:') ? r.photo : `data:image/jpeg;base64,${r.photo}`;
      doc.addImage(imgData, 'JPEG', W - 46, 4, 30, 30, undefined, 'FAST');
    } catch { /* skip */ }
  }

  // Status badge
  const isSuccess = record.status === 'success';
  doc.setFillColor(isSuccess ? 220 : 254, isSuccess ? 252 : 226, isSuccess ? 231 : 226);
  doc.roundedRect(14, 44, 50, 9, 2, 2, 'F');
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(isSuccess ? 22 : 220, isSuccess ? 163 : 38, isSuccess ? 74 : 38);
  doc.text(isSuccess ? 'VERIFIED' : 'FAILED', 18, 50);

  // Identity fields
  doc.setTextColor(15, 23, 42);
  const fields = [
    ['NIN', record.nin ? `****${record.nin.slice(-4)}` : '—'],
    ['First Name', r.firstName || '—'],
    ['Last Name', r.lastName || '—'],
    ['Middle Name', r.middleName || '—'],
    ['Date of Birth', r.dateOfBirth || '—'],
    ['Gender', r.gender || '—'],
    ['Phone Number', r.phoneNumber || '—'],
    ['Address', r.address || '—'],
    ['State of Origin', r.stateOfOrigin || '—'],
    ['LGA', r.lga || '—'],
    ['Nationality', r.nationality || 'Nigerian'],
    ['Religion', r.religion || '—'],
    ['Marital Status', r.maritalStatus || '—'],
    ['Watch Listed', r.watchListed || 'No'],
  ];

  autoTable(doc, {
    startY: 58,
    head: [['Field', 'Value']],
    body: fields,
    theme: 'striped',
    headStyles: { fillColor: [79, 70, 229], textColor: 255, fontStyle: 'bold', fontSize: 10 },
    alternateRowStyles: { fillColor: [240, 239, 255] },
    styles: { fontSize: 10, cellPadding: 4 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 55 } },
    margin: { left: 14, right: 14 },
  });

  // Footer
  const pageH = doc.internal.pageSize.getHeight();
  doc.setFillColor(248, 250, 252);
  doc.rect(0, pageH - 18, W, 18, 'F');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.setFont('helvetica', 'normal');
  doc.text('This certificate is generated by the Lucred Credit Engine Developer Portal. For official use only.', 14, pageH - 8);
  doc.text('Page 1 of 1', W - 14, pageH - 8, { align: 'right' });

  const name = `${r.firstName || ''} ${r.lastName || ''}`.trim() || 'unknown';
  doc.save(`nin-certificate-${name.replace(/\s+/g, '-').toLowerCase()}.pdf`);
}
