import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export default function exportSummaryPDF({ stats, orgName, isAdmin = false }) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, W, 42, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(isAdmin ? 'Platform Overview Report' : 'Dashboard Summary Report', 14, 17);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  if (orgName) doc.text(`Organisation: ${orgName}`, 14, 25);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 31);
  doc.text('Lucred Credit Engine · Confidential', 14, 37);

  let y = 50;

  const sectionHead = (label) => {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(109, 40, 217);
    doc.text(label, 14, y);
    y += 6;
  };

  if (isAdmin) {
    sectionHead('MFI Clients');
    doc.autoTable({
      startY: y,
      body: [
        ['Total MFI Clients', stats?.totalClients ?? '—'],
        ['Active Clients', stats?.activeClients ?? '—'],
        ['Suspended Clients', stats ? (stats.totalClients - stats.activeClients) : '—'],
        ['Total API Requests (platform)', stats?.totalRequests?.toLocaleString() ?? '—'],
      ],
      theme: 'striped',
      headStyles: { fillColor: [15, 23, 42] },
      alternateRowStyles: { fillColor: [248, 246, 255] },
      styles: { fontSize: 10, cellPadding: 4 },
      columnStyles: { 0: { fontStyle: 'bold', cellWidth: 90 } },
      margin: { left: 14, right: 14 },
    });
    y = doc.lastAutoTable.finalY + 12;
  }

  sectionHead('Analysis Volume');
  doc.autoTable({
    startY: y,
    head: [['Metric', 'Total', 'Failed']],
    body: [
      ['Customers (Borrower Profiles)', stats?.customers ?? stats?.totalCustomers ?? '—', '—'],
      ['Statement Analyses', stats?.statements?.total ?? '—', stats?.statements?.failed ?? '—'],
      ['BVN Verifications', stats?.bvn?.total ?? '—', stats?.bvn?.failed ?? '—'],
      ['NIN Verifications', stats?.nin?.total ?? '—', stats?.nin?.failed ?? '—'],
      ['Credit Bureau Checks', stats?.bureau?.total ?? '—', stats?.bureau?.failed ?? '—'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [109, 40, 217], textColor: 255, fontStyle: 'bold', fontSize: 10 },
    alternateRowStyles: { fillColor: [248, 246, 255] },
    styles: { fontSize: 10, cellPadding: 4 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 90 } },
    margin: { left: 14, right: 14 },
  });
  y = doc.lastAutoTable.finalY + 14;

  // Endpoint breakdown (admin only)
  if (isAdmin && stats?.byEndpoint?.length > 0) {
    sectionHead('Requests by Endpoint');
    doc.autoTable({
      startY: y,
      head: [['Endpoint', 'Request Count']],
      body: stats.byEndpoint.map((e) => [e._id, e.count]),
      theme: 'grid',
      headStyles: { fillColor: [15, 23, 42], textColor: 255, fontSize: 9 },
      styles: { fontSize: 9, cellPadding: 3 },
      margin: { left: 14, right: 14 },
    });
  }

  // Footer
  const pageH = doc.internal.pageSize.getHeight();
  doc.setFillColor(248, 250, 252);
  doc.rect(0, pageH - 18, W, 18, 'F');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by the Lucred Credit Engine Developer Portal. For internal use only.', 14, pageH - 8);
  doc.text('Page 1 of 1', W - 14, pageH - 8, { align: 'right' });

  const slug = isAdmin ? 'platform' : (orgName || 'dashboard').toLowerCase().replace(/\s+/g, '-');
  doc.save(`lucred-summary-${slug}-${new Date().toISOString().slice(0, 10)}.pdf`);
}
