import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export default function exportBVNCertPDF(record) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();
  const r = record.result || {};

  // Header bar
  doc.setFillColor(109, 40, 217);
  doc.rect(0, 0, W, 38, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('BVN Verification Certificate', 14, 16);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 24);
  doc.text(`Lucred Credit Engine · Confidential`, 14, 30);

  // Photo
  let photoX = W - 14;
  if (r.image) {
    try {
      const imgData = r.image.startsWith('data:') ? r.image : `data:image/jpeg;base64,${r.image}`;
      doc.addImage(imgData, 'JPEG', W - 46, 4, 30, 30, undefined, 'FAST');
      photoX = W - 50;
    } catch { /* skip if corrupt */ }
  }

  // Status badge
  const isSuccess = record.status === 'success';
  doc.setFillColor(isSuccess ? 220 : 254, isSuccess ? 252 : 226, isSuccess ? 231 : 226);
  doc.roundedRect(14, 44, 50, 9, 2, 2, 'F');
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(isSuccess ? 22 : 220, isSuccess ? 163 : 38, isSuccess ? 74 : 38);
  doc.text(isSuccess ? '✓ VERIFIED' : '✗ FAILED', 18, 50);

  // Identity fields
  doc.setTextColor(15, 23, 42);
  const fields = [
    ['BVN', record.bvn ? `****${record.bvn.slice(-4)}` : '—'],
    ['First Name', r.firstName || '—'],
    ['Last Name', r.lastName || '—'],
    ['Middle Name', r.middleName || '—'],
    ['Date of Birth', r.dateOfBirth || '—'],
    ['Gender', r.gender || '—'],
    ['Phone Number', r.phoneNumber || '—'],
    ['Nationality', r.nationality || 'Nigerian'],
    ['State of Origin', r.stateOfOrigin || '—'],
    ['LGA', r.lga || '—'],
    ['Enrollment Bank', r.enrollmentBank || '—'],
    ['Watch Listed', r.watchListed || 'No'],
  ];

  doc.autoTable({
    startY: 58,
    head: [['Field', 'Value']],
    body: fields,
    theme: 'striped',
    headStyles: { fillColor: [109, 40, 217], textColor: 255, fontStyle: 'bold', fontSize: 10 },
    alternateRowStyles: { fillColor: [248, 246, 255] },
    styles: { fontSize: 10, cellPadding: 4 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 55 } },
    margin: { left: 14, right: 14 },
  });

  // Footer
  const pageH = doc.internal.pageSize.getHeight();
  doc.setFillColor(248, 250, 252);
  doc.rect(0, pageH - 18, W, 18, 'F');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.setFont('helvetica', 'normal');
  doc.text('This certificate is generated by the Lucred MFI Developer Portal. For official use only.', 14, pageH - 8);
  doc.text(`Page 1 of 1`, W - 14, pageH - 8, { align: 'right' });

  const name = `${r.firstName || ''} ${r.lastName || ''}`.trim() || 'unknown';
  doc.save(`bvn-certificate-${name.replace(/\s+/g, '-').toLowerCase()}.pdf`);
}
