import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export default function exportBureauPDF(record) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();
  const d = record.result || {};
  const sum = d.summary || d;

  // Header
  doc.setFillColor(245, 158, 11);
  doc.rect(0, 0, W, 38, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Credit Bureau Report', 14, 16);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 24);
  doc.text(`Lucred Credit Engine · Confidential`, 14, 30);

  // Credit score banner
  const score = d.creditScore ?? sum.creditScore;
  if (score !== undefined) {
    const scoreColor = score >= 700 ? [22, 163, 74] : score >= 500 ? [245, 158, 11] : [220, 38, 38];
    doc.setFillColor(...scoreColor);
    doc.roundedRect(14, 44, 80, 22, 3, 3, 'F');
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text(String(score), 22, 58);
    doc.setFontSize(9);
    doc.text('CREDIT SCORE', 22, 64);

    const grade = score >= 700 ? 'Good' : score >= 500 ? 'Fair' : 'Poor';
    doc.setFontSize(12);
    doc.text(grade, 70, 57, { align: 'center' });
  }

  // Summary table
  const summaryFields = [
    ['BVN (masked)', record.bvn ? `****${record.bvn.slice(-4)}` : '—'],
    ['Total Facilities', d.totalFacilities ?? sum.totalFacilities ?? '—'],
    ['Active Loans', d.activeLoans ?? sum.activeLoans ?? '—'],
    ['Closed Loans', d.closedLoans ?? sum.closedLoans ?? '—'],
    ['Total Outstanding', d.totalOutstanding ?? sum.totalOutstanding ?? '—'],
    ['Overdue Amount', d.overdueAmount ?? sum.overdueAmount ?? '—'],
    ['Delinquency Status', d.delinquencyStatus ?? sum.delinquencyStatus ?? '—'],
    ['Verification Status', record.status],
    ['Date Checked', new Date(record.createdAt).toLocaleString()],
  ];

  doc.autoTable({
    startY: 72,
    head: [['Field', 'Value']],
    body: summaryFields,
    theme: 'striped',
    headStyles: { fillColor: [245, 158, 11], textColor: 255, fontStyle: 'bold', fontSize: 10 },
    alternateRowStyles: { fillColor: [255, 251, 235] },
    styles: { fontSize: 10, cellPadding: 4 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 65 } },
    margin: { left: 14, right: 14 },
  });

  // Loan facilities table
  const loans = d.loanFacilities || d.loans || [];
  if (loans.length > 0) {
    doc.autoTable({
      startY: doc.lastAutoTable.finalY + 10,
      head: [['Lender', 'Type', 'Amount', 'Outstanding', 'Status', 'Start Date']],
      body: loans.map((l) => [
        l.lender || l.bankName || '—',
        l.loanType || l.type || '—',
        l.amount ?? '—',
        l.outstanding ?? l.outstandingBalance ?? '—',
        l.status || '—',
        l.startDate || l.disbursementDate || '—',
      ]),
      theme: 'grid',
      headStyles: { fillColor: [15, 23, 42], textColor: 255, fontSize: 9 },
      styles: { fontSize: 9, cellPadding: 3 },
      margin: { left: 14, right: 14 },
      didDrawPage: (data) => {
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(15, 23, 42);
        doc.text('Loan Facilities', 14, data.settings.startY - 4);
      },
    });
  }

  // Repayment history table
  const history = d.repaymentHistory || d.history || [];
  if (history.length > 0) {
    doc.autoTable({
      startY: doc.lastAutoTable.finalY + 12,
      head: [['Month', 'Status', 'Amount', 'Days Past Due']],
      body: history.map((h) => [
        h.month || h.date || '—',
        h.status || '—',
        h.amount ?? '—',
        h.daysPastDue ?? '—',
      ]),
      theme: 'grid',
      headStyles: { fillColor: [109, 40, 217], textColor: 255, fontSize: 9 },
      styles: { fontSize: 9, cellPadding: 3 },
      margin: { left: 14, right: 14 },
      didDrawPage: (data) => {
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(15, 23, 42);
        doc.text('Repayment History', 14, data.settings.startY - 4);
      },
    });
  }

  // Footer on all pages
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const pageH = doc.internal.pageSize.getHeight();
    doc.setFillColor(248, 250, 252);
    doc.rect(0, pageH - 18, W, 18, 'F');
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.setFont('helvetica', 'normal');
    doc.text('This report is generated by the Lucred MFI Developer Portal. For official use only.', 14, pageH - 8);
    doc.text(`Page ${i} of ${pageCount}`, W - 14, pageH - 8, { align: 'right' });
  }

  const bvnSuffix = record.bvn ? record.bvn.slice(-4) : 'report';
  doc.save(`credit-bureau-${bvnSuffix}.pdf`);
}
